management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health , loggers

  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      cryptocurrency-service:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG
